//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramTreningowyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhotoSet
    {
        public PersonPhotoSet()
        {

        }
        public PersonPhotoSet(int personTreningDaySetId, byte[] photo)
        {
            PersonTreningDaySetId = personTreningDaySetId;
            Photo = photo;
        }
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public int PersonTreningDaySetId { get; set; }
    
        public virtual PersonTreningDaySet PersonTreningDaySet { get; set; }
    }
}
