//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramTreningowyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTreningDaySet
    {
        private DateTime? selectedDate;
        private string diete;
        private double? wage;
        private string workOut;
        private string suplementation;

        public PersonTreningDaySet()
        {
            this.PersonPhotoSet = new HashSet<PersonPhotoSet>();
        }

       

        public PersonTreningDaySet(DateTime? date, string diet, int personSetId, double? weight, string exercises, string supplementation)
        {
            Date = date;
            Diet = diet;
            PersonSetId = personSetId;
            Weight = weight;
            Exercises = exercises;
            Supplementation = supplementation;
            this.PersonPhotoSet = new HashSet<PersonPhotoSet>();
        }

        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Exercises { get; set; }
        public string Diet { get; set; }
        public string Supplementation { get; set; }
        public int PersonSetId { get; set; }
    
        public virtual PersonSet PersonSet { get; set; }
        public virtual ICollection<PersonPhotoSet> PersonPhotoSet { get; set; }
    }
}
