//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramTreningowyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSet
    {
        public PersonSet()
        {
            this.PersonNoTreningDaySet = new HashSet<PersonNoTreningDaySet>();
            this.PersonTreningDaySet = new HashSet<PersonTreningDaySet>();
        }
        public PersonSet(string login,string password)
        {
            this.PersonNoTreningDaySet = new HashSet<PersonNoTreningDaySet>();
            this.PersonTreningDaySet = new HashSet<PersonTreningDaySet>();
            Login = login;
            Password = password;
        }


        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<PersonNoTreningDaySet> PersonNoTreningDaySet { get; set; }
        public virtual ICollection<PersonTreningDaySet> PersonTreningDaySet { get; set; }
    }
}
