//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramTreningowyWPF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkOut2Container : DbContext
    {
        public WorkOut2Container()
            : base("name=WorkOut2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PersonSet> PersonSetSet { get; set; }
        public DbSet<PersonTreningDaySet> PersonTreningDaySetSet { get; set; }
        public DbSet<PersonPhotoSet> PersonPhotoSetSet { get; set; }
        public DbSet<PersonNoTreningDaySet> PersonNoTreningDaySetSet { get; set; }
    }
}
